name: Deploy Tasleemat Documentation to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install MkDocs Material & Extensions
        run: |
          pip install mkdocs-material pymdown-extensions

      - name: Deploy MkDocs to GitHub Pages
        run: |
          mkdocs gh-deploy --force
